blank_issues_enabled: false

contact_links:
  - name: 📚 MMClassification Documentation (官方文档)
    url: https://mmclassification.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
  - name: 💬 General questions (寻求帮助)
    url: https://github.com/open-mmlab/mmclassification/discussions
    about: Ask general usage questions and discuss with other MMClassification community members
  - name: 🌐 Explore OpenMMLab (官网)
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
